[versions]
gradle-android = "8.2.2"
gradle-binary-compat = "0.16.3"
gradle-kmp-configuration = "0.3.2"
gradle-kotlin = "1.9.24"
gradle-publish-maven = "0.29.0"
gradle-publish-npm = "3.4.1"

kmp-tor-common = "2.1.0"

# tests & tools
androidx-test-core = "1.5.0"
androidx-test-runner = "1.5.2"

encoding = "2.2.2"

kotlincrypto-hash = "0.5.3"
kotlinx-cli = "0.3.6"
kotlinx-coroutines = "1.8.1"
kotlinx-datetime = "0.5.0"

okio = "3.7.0"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }
gradle-kmp-configuration = { module = "io.matthewnelson:gradle-kmp-configuration-plugin", version.ref = "gradle-kmp-configuration" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "gradle-kotlin" }
gradle-publish-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-publish-maven" }

kmp-tor-common-api = { module = "io.matthewnelson.kmp-tor:common-api", version.ref = "kmp-tor-common" }
kmp-tor-common-core = { module = "io.matthewnelson.kmp-tor:common-core", version.ref = "kmp-tor-common" }
kmp-tor-common-lib-locator = { module = "io.matthewnelson.kmp-tor:common-lib-locator", version.ref = "kmp-tor-common" }

# tests & tools
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }

encoding-base16 = { module = "io.matthewnelson.encoding:base16", version.ref = "encoding" }
encoding-base64 = { module = "io.matthewnelson.encoding:base64", version.ref = "encoding" }

kotlincrypto-hash-sha2 = { module = "org.kotlincrypto.hash:sha2", version.ref = "kotlincrypto-hash" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

okio-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakeFileSystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
okio-node = { module = "com.squareup.okio:okio-nodefilesystem", version.ref = "okio" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle-android" }
binary-compat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "gradle-binary-compat" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
publish-npm = { id = "dev.petuska.npm.publish", version.ref = "gradle-publish-npm" }
